// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package app

// Injectors from wire.go:

func InitializeApp(cfgFile string) (*ProfileApp, error) {
	v, err := ReadConf(cfgFile)
	if err != nil {
		return nil, err
	}
	profileApp, err := NewProfileApp(v)
	if err != nil {
		return nil, err
	}
	return profileApp, nil
}
